### PR TITLE
#162192941 set up environment for running tests

### PR DESCRIPTION
**Pull request by kakaemma**
#### What does this PR do?
This PR sets up an environment for running tests,
It also adds tests to the existing codebase.

### How should this be manually tested?
Clone the application with `git clone `
install application dependencies with `npm install`
Run tests with `npm run test -- -u --coverage`

#### What are the relevant pivotal tracker stories?
[#162192941](https://www.pivotaltracker.com/story/show/162192941)

#### Any background context you want to add?
N/A

### CODE REVIEW

**Review by RonKbS — COMMENTED** [review]
Nice work @kakaemma. Please add your package-lock.json to the .gitignore.

**Comment by kakaemma** [comment]
Thank you @RonKbS , let me work on it

**Comment by kakaemma** [comment]
@RonKbS , I have added the `package-lock.json` to .gitignore

**Review by RonKbS — APPROVED** [review]
LGTM

**Pull request merged**
